// Code generated by protoc-gen-go. DO NOT EDIT.
package grpctrigger

import (
	"google.golang.org/grpc"
)

// Method to register the gRPC server methods
func registerServerMethods(s *grpc.Server) {
}
